FROM alpine:3.20

RUN apk add --no-cache bash curl jq tzdata busybox-suid

WORKDIR /app
COPY scripts/backup_all_volumes.sh /app/backup_all_volumes.sh
RUN chmod +x /app/backup_all_volumes.sh

# Cron log to stdout
RUN mkdir -p /var/log && touch /var/log/cron.log

# Default timezone 
ENV TZ=Europe/Amsterdam

# Execute cron foreground + tail log
CMD sh -c "crond -f -l 8 && tail -f /var/log/cron.log"
